### ISSUE TITLE
Repositories and things

### ISSUE THREAD

**Issue by d-rez** [funkytechmonkey/razer-leviathan#1]
Do you have any way of providing proof that this was actually put together by or in collaboration with Razer?

I'm pretty sure you're also violating github's terms of use by uploading proprietary compiled code here.

This repo's history looks sketchy as hell. Is this firmware available through Razer support?

Sorry for being suspicious but I've seen way too many harmful projects.

**Comment by stennie** [comment]
@d-rez Agree the repo history looks very sketchy! Original commits (before 2017 / [https://github.com/funkytechmonkey/razer-leviathan/commit/a69b93dbc4887aaf9da9bccc93d341a18e676dae](https://github.com/funkytechmonkey/razer-leviathan/commit/a69b93dbc4887aaf9da9bccc93d341a18e676dae)) appear to be entirely unrelated files that were later removed. It looks like all of the changes were done via the web interface with default commit messages.

I contacted Razer support and asked if this repo provided a legit update. Razer support did not explicitly confirm this repo, but did provide a download link for a firmware update (http://rzr.to/FiZqH) which includes similar files to the [Razer Leviathan Update](https://github.com/funkytechmonkey/razer-leviathan/tree/master/Razer%20Leviathan%20Updater) directory. I asked about publicly posting or commenting on this update but they are apparently only willing to provide firmware updates via a support request at the moment.

Checksums from the files downloaded from Razer support:

```
MD5 (How to access the Razer Leviathan Service USB port and update the soundb....pdf) = 0ffc4b04552f5e2e59fd65fa738d3d3f
MD5 (beethoven11_v1.0.0.0.mdu) = 141cca810848c3d7a8b984d82830c921
```

Checksums from this GitHub repo:

```
MD5 (How to access the Razer Leviathan Service USB port and update the soundb....pdf) = a68409836d92754c6b232fbfc950ac84
MD5 (beethoven11_v1.0.0.0.mdu) = 141cca810848c3d7a8b984d82830c921
```

The checksums on the mdu (firmware update) match; the PDF checksums differ but appear to be the same content printed from Word on different days. I suspect the commit history oddities are due to a new user unfamiliar with `git`.

I updated my Leviathan using the file provided by Razer (rzr.to link above). All appeared to work fine: this successfully disabled the auto off feature (huzzah!) and nothing has burst into flames yet.

Related discussion on Razer Insider:
 - [Razer Leviathan auto power off [fix]
](https://insider.razerzone.com/index.php?threads/razer-leviathan-auto-power-off-fix.5128/page-3)
 - [Razer Leviathan auto power off [FIRMWARE FIX]](https://insider.razerzone.com/index.php?threads/razer-leviathan-auto-power-off-firmware-fix.21208/)

Regards,
Stennie

**Comment by d-rez** [comment]
@stennie I've actually also contacted Razer and got these links, they also did not confirm or deny this repo, they simply skipped my question lol

I've linked them on [Razer subreddit wiki](https://www.reddit.com/r/razer/wiki/index#wiki_leviathan)
